### ISSUE TITLE
InferenceLogger from the GUI package should be pulled into the core

### ISSUE THREAD

**Issue by freemo** [opennars/opennars#107]
This logger has usefulness outside of the GUI, should probably exist in the core.

**Comment by patham9** [comment]
Not sure here. If a nars_lab analyzer want to log something of core that's fine it can do so, but why would core need to do that assuming it works?

**Comment by freemo** [comment]
core currently uses InferenceLogger in two places. I removed it since they were unreachable code anyway. But from what I could tell InferenceLogger lets you log/display core objects. Its a tool that anyone who has core might want to use to debug their application. Not sure why it wouldnt be in core really. I have no issue with leaving it out either, just seems "awkward" to have to include a whole package just to be able to get some debugging output.

**Comment by patham9** [comment]
Indeed, in this case no one was using it over the last 4 years. But for the GUI it's ok to support it. I followed an a bit different philosophy in nars_core and nars_gui/nars_lab: 

nars_core staying as minimal as possible meaning everything that does not contribute to "NARS running" was removed from there. Also this is the part that is used in applications, so it needs to be as well documented, well tested and as fast as possible, will try my best in summer to catch up here.

 nars_gui:  I didn't enforce anything there, and didn't change it much in the last 4 years. But when someone found something annoying, I usually immediately fixed it, it didn't demand test cases to make the GUI bug-free as there are no deep ideas or complex algorithms involved there.

nars_lab: I didn't enforce anything there also, and don't mind if it grows and grows. Whatever NARS-applications one wants to try,  they can go there. Additionally, those that work well, were always added to the Launcher GUI, so that people can run it from the release .jar without demanding knowledge of how to run particular examples. As in nars_gui, not having testcases in nars_lab didn't cause problems so far, as it can be directly visually seen whether an example works or not, differently than in nars_core where extensive testing, profiling and documenting is very important.

My work in the last 4 years was mostly in nars_core (which was created by Pei and then performance-optimized by automenta), and in nars_lab for adding new programmatic examples. nars_gui was fully created by automenta, I didn't touch much there as I am quite happy with the GUI.

**Comment by freemo** [comment]
Sounds like a good approach. I think having a slim core is important. Just
seemed at the time the logger made sense there as it seemed critical for
debugging. But I retract that assertion based on your statements. Feel free
to close this ticket.
