### ISSUE TITLE
Catch narsese parser exceptions

### ISSUE THREAD

**Issue by PtrMan** [opennars/opennars#249]
The program crashes if there is an exception thrown by the parser if it is instructed to parse invalid narsese.

**Comment by patham9** [comment]
The user interface should handle the exception, creating a message box showing the user what he did wrong (for the beginning that his input was not right), in such a case the input should also not be deleted from the input dialog so that the user can make the necessary modifications. -> issue of nars-gui.

**Comment by patham9** [comment]
fixed by https://github.com/opennars/opennars/pull/303
