### ISSUE TITLE
Ability to disable output text to IO window

### ISSUE THREAD

**Issue by TonyLo1** [opennars/opennars#27]
Currently it can be closed but it can't be reopened without restarting. Disabling the text output increases the inference performance.

**Comment by patham9** [comment]
Is again a matter of silence level.

**Comment by automenta** [comment]
you should be able to create additional "Output" windows from the view menu. as many as you like, they willl all receive events but display according to their individual filter settings. global volume in the control panel affects everything though so it might be helpful to add a local volume filter. but i am thinking about a rate limiter which, instead of being a hard priority gate, adapts to prevent a rate limit of output events (ex: no more than 10 outputs per cycle, or 10 outputs per minute). maybe this rate limiting can apply to other parts besides Output events, which are like an internal type of Operation execution.

**Comment by patham9** [comment]
Closed (Silence level is supported)
