### ISSUE TITLE
Unexpected truth value update in temporal Analogy

### ISSUE THREAD

**Issue by l591326240** [opennars/opennars#33]
```
IN: <<robin --> bird> <|> <robin --> animal>>. 
IN: <<robin --> [flying]> =\> <robin --> bird>>.

<<robin --> [flying]> =\> <robin --> animal>>. %1.00;0.81%
<<robin --> [flying]> =\> <robin --> animal>>. %1.00;0.81%

<<robin --> [flying]> =\> <robin --> bird>>. %1.00;0.73% <--(Unexpected)

Confidence should not be updated to 0.73. 
```

**Comment by patham9** [comment]
its not "updated", its just a following inference of
<<robin --> [flying]> =\> <robin --> animal>>. %1.00;0.81%
with
<<robin --> bird> <|> <robin --> animal>>. 
leading to
<<robin --> [flying]> =\> <robin --> bird>>. %1.00;0.73% 
which is allowed because overlapping base check is not applied on results of strong inference rules as I discussed with Pei some months ago.

Best regards,
Patrick

**Comment by l591326240** [comment]
Ah, okay. Maybe Dr. Wang didn't realize this when I talked about this problem with him, he said this is an issue because the truth value of <<robin --> [flying]> =\> <robin --> bird>>. should keep %1.00;0.90%.

I think this is why he asked me to post all the issues here then you guys can see them.

If this is not a problem then I will close this issue, thanks for the comment.

Regards,

Xiang
